<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Thanksgiving Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'pastorkristi@alpingbethel.org',
		'to' => 'pastorkristi@alpingbethel.org'
	),
	'fields' => array(
		'custom_U10335' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U10343' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Phone\' is required.'
			)
		),
		'custom_U10370' => array(
			'order' => 4,
			'type' => 'checkboxgroup',
			'label' => 'What would you like to help with?',
			'required' => true,
			'optionItems' => array(
				'Cooking/Set up (1:00-3:30PM)',
				'Serving (3:30-5:00PM)',
				'Clean up (5:00-6:00PM)'
			),
			'errors' => array(
				'required' => 'Field \'What would you like to help with?\' is required.',
				'format' => 'Field \'What would you like to help with?\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
