<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Craft Fair Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'https://pushpay.com/pay/alpinebethel/7mY1Q8PVt_Mv43XQ62AlpQ',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'youth@alpinebethel.org',
		'to' => 'youth@alpinebethel.org'
	),
	'fields' => array(
		'custom_U14826' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U14808' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Phone Number',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Phone Number\' is required.'
			)
		),
		'custom_U14813' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Business Name',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U14839' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Website',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U14834' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'What Will You Be Selling',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'What Will You Be Selling\' is required.'
			)
		),
		'custom_U14930' => array(
			'order' => 7,
			'type' => 'checkbox',
			'label' => 'Requires Electricity',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
