<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Volunteer Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'pastorkristi@alpinebethel.org',
		'to' => 'pastorkristi@alpinebethel.org'
	),
	'fields' => array(
		'custom_U7567' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U7557' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Cell Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Cell Phone\' is required.'
			)
		),
		'custom_U15062' => array(
			'order' => 5,
			'type' => 'checkbox',
			'label' => 'Mom\'s Connection (Fridays 9:30am)',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U15146' => array(
			'order' => 6,
			'type' => 'checkbox',
			'label' => 'Sermon Based w/ Pfeiffer  (Thursday 10:00am)',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U15158' => array(
			'order' => 7,
			'type' => 'checkbox',
			'label' => 'Soul Detox (Wednesdays 7:00pm)',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U20519' => array(
			'order' => 8,
			'type' => 'checkbox',
			'label' => 'Sermon Based w/ Pettruccelli (Wednesdays 7:00pm)',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U24393' => array(
			'order' => 9,
			'type' => 'checkbox',
			'label' => 'Sermon Based w/ Rodgers (Saturdays 7:00pm)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Sermon Based w/ Rodgers (Saturdays 7:00pm)\' is required.'
			)
		),
		'custom_U24405' => array(
			'order' => 10,
			'type' => 'checkbox',
			'label' => 'Church History (Sundays 9:00am)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Church History (Sundays 9:00am)\' is required.'
			)
		),
		'custom_U7842' => array(
			'order' => 4,
			'type' => 'checkboxgroup',
			'label' => 'Life Group(s) you will be attending',
			'required' => false,
			'optionItems' => array(
				'War Room (Wednesdays 9:30am)',
				'Sermon Based w/ Roedell (Wednesdays 7:00pm)',
				'Girls With Swords (Wednesday 7:00pm)',
				'Romans (Wednesdays 6:00pm)',
				'Girls With Swords ONLINE (Thursdays)',
				'Anchored Men (Thursdays 7:00pm)'
			),
			'errors' => array(
				'format' => 'Field \'Life Group(s) you will be attending\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
